### PR TITLE
fixed error

### PR DESCRIPTION
**Pull request by sambritton**
Added python_test folder.
Fixed error of E_regulation being overwritten in module.cpp
Removed egg-info

### CODE REVIEW

**Comment by sambritton** [comment]
Is there a modification that can be done to this pull request or should I make a new one?

**Comment by ashermancinelli** [comment]
Yes, you can just `git rm` the binaries and push that commit.

**Comment by ashermancinelli** [comment]
You don't have to close the PR, you can just push additional commits to the branch.

**Comment by sambritton** [comment]
I was trying to do that. So if I push new changes then I don't have to
update the pull request?

**Comment by ashermancinelli** [comment]
Nope! Please reopen the pull request, remove the binaries and build files from your branch, push those changes, and then I can merge your branch.

**Pull request closed without merging**
